//Analytic
import { useEffect, useState } from "react";
import {
    LineChart,
    Line,
    BarChart,
    Bar,
    PieChart,
    Pie,
    Cell,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    Legend,
    ResponsiveContainer
} from "recharts";
import { getAnalytics } from "../api";

function Analytics() {
    const [analytics, setAnalytics] = useState({ summary: {}, portfolioData: [], stockPerformance: [], portfolioDistribution: [] });

    useEffect(() => {
        getAnalytics().then(setAnalytics).catch(() => {});
    }, []);

    const { summary, portfolioData, stockPerformance, portfolioDistribution } = analytics;

    return (
        <div className="analytics-page">

            <div className="page-header">

                <div>
                    <h1>Analytics</h1>

                    <p>
                        Analyze your portfolio performance
                        and investment distribution.
                    </p>
                </div>

            </div>

            {/* Summary */}

            <div className="stats-grid">

                <div className="stat-card">

                    <span>Total Investment</span>

                    <h2>
                        ₹{(summary.investment || 0).toLocaleString("en-IN")}
                    </h2>

                </div>

                <div className="stat-card">

                    <span>Current Value</span>

                    <h2>
                        ₹{(summary.currentValue || 0).toLocaleString("en-IN")}
                    </h2>

                </div>

                <div className="stat-card">

                    <span>Total Return</span>

                    <h2 className="positive">
                        +{summary.returnPercent || 0}%
                    </h2>

                </div>

                <div className="stat-card">

                    <span>Total Profit</span>

                    <h2 className="positive">
                        +₹{(summary.profit || 0).toLocaleString("en-IN")}
                    </h2>

                </div>

            </div>


            {/* Portfolio Performance */}

            <div className="analytics-card">

                <div className="section-header">

                    <div>
                        <h2>
                            Portfolio Performance
                        </h2>

                        <p>
                            Growth of your portfolio
                            over time.
                        </p>
                    </div>

                    <select>
                        <option>6 Months</option>
                        <option>1 Year</option>
                        <option>3 Years</option>
                    </select>

                </div>

                <div className="chart-container">

                    <ResponsiveContainer
                        width="100%"
                        height={350}
                    >

                        <LineChart
                            data={portfolioData}
                        >

                            <CartesianGrid
                                strokeDasharray="3 3"
                            />

                            <XAxis
                                dataKey="month"
                            />

                            <YAxis />

                            <Tooltip />

                            <Line
                                type="monotone"
                                dataKey="value"
                                stroke="#2563eb"
                                strokeWidth={3}
                                dot
                            />

                        </LineChart>

                    </ResponsiveContainer>

                </div>

            </div>


            {/* Two charts */}

            <div className="analytics-grid">

                {/* Stock Performance */}

                <div className="analytics-card">

                    <h2>
                        Stock Performance
                    </h2>

                    <p>
                        Profit generated by each stock.
                    </p>

                    <div className="chart-container">

                        <ResponsiveContainer
                            width="100%"
                            height={300}
                        >

                            <BarChart
                                data={stockPerformance}
                            >

                                <CartesianGrid
                                    strokeDasharray="3 3"
                                />

                                <XAxis
                                    dataKey="name"
                                />

                                <YAxis />

                                <Tooltip />

                                <Bar
                                    dataKey="profit"
                                    fill="#2563eb"
                                />

                            </BarChart>

                        </ResponsiveContainer>

                    </div>

                </div>


                {/* Portfolio Distribution */}

                <div className="analytics-card">

                    <h2>
                        Portfolio Distribution
                    </h2>

                    <p>
                        Percentage invested in each stock.
                    </p>

                    <div className="chart-container">

                        <ResponsiveContainer
                            width="100%"
                            height={300}
                        >

                            <PieChart>

                                <Pie
                                    data={portfolioDistribution}
                                    dataKey="value"
                                    nameKey="name"
                                    cx="50%"
                                    cy="50%"
                                    outerRadius={100}
                                    label
                                >

                                    {portfolioDistribution.map(
                                        (entry, index) => (
                                            <Cell
                                                key={`cell-${index}`}
                                                fill={[
                                                    "#2563eb",
                                                    "#16a34a",
                                                    "#f59e0b",
                                                    "#dc2626"
                                                ][index]}
                                            />
                                        )
                                    )}

                                </Pie>

                                <Tooltip />

                                <Legend />

                            </PieChart>

                        </ResponsiveContainer>

                    </div>

                </div>

            </div>


            {/* Analytics table */}

            <div className="analytics-card">

                <h2>
                    Stock Analysis
                </h2>

                <div className="table-container">

                    <table>

                        <thead>

                            <tr>
                                <th>Stock</th>
                                <th>Investment</th>
                                <th>Current Value</th>
                                <th>Profit</th>
                                <th>Return</th>
                            </tr>

                        </thead>

                        <tbody>

                            <tr>

                                <td>TCS</td>

                                <td>
                                    ₹35,000
                                </td>

                                <td>
                                    ₹38,200
                                </td>

                                <td className="positive">
                                    +₹3,200
                                </td>

                                <td className="positive">
                                    +9.14%
                                </td>

                            </tr>

                            <tr>

                                <td>INFY</td>

                                <td>
                                    ₹30,000
                                </td>

                                <td>
                                    ₹33,000
                                </td>

                                <td className="positive">
                                    +₹3,000
                                </td>

                                <td className="positive">
                                    +10%
                                </td>

                            </tr>

                            <tr>

                                <td>RELIANCE</td>

                                <td>
                                    ₹21,000
                                </td>

                                <td>
                                    ₹21,750
                                </td>

                                <td className="positive">
                                    +₹750
                                </td>

                                <td className="positive">
                                    +3.57%
                                </td>

                            </tr>

                        </tbody>

                    </table>

                </div>

            </div>

        </div>
    );
}

export default Analytics;